### ISSUE TITLE
 "Go to Resource" button should be hidden for V2 NGSI APIs 

### ISSUE THREAD

**Issue by Nisha1293** [conwetlab/ckanext-ngsiview#13]
**Issue Description:**
When I created a new resource on the CKAN UI with the format fiware-ngsi and resource is created successfully. Data preview is working  fine as shown in below image. But on that screen there is one button visible with name "Go to Resource"
as shown below.
 
![ngsi_view](https://user-images.githubusercontent.com/89568228/179202735-47225c89-a177-422d-8b34-ebb79d1ccddc.png)

On clicking on the "Go to Resource" button , it is giving the below error.

**Error:**
<pre>
<ams:fault xmlns:ams="http://wso2.org/apimanager/security">
<ams:code>900902</ams:code>
<ams:message>Missing Credentials</ams:message>
<ams:description>Required OAuth credentials not provided. Make sure your API invocation call has a header: "Authorization: Bearer ACCESS_TOKEN"</ams:description>
</ams:fault>
</pre>

**Investigation:**
On the source code analysis,  We found that there are two below files which has the functionality of hiding the "Go to Resource" button for V1 APIs.

1. https://github.com/conwetlab/ckanext-right_time_context/blob/master/ckanext/right_time_context/templates/package/resource_read.html
<pre>
**Line no 8:**
{% if res.url.lower().find('/querycontext') == -1 and res.url.lower().find('/contextentities/') == -1 %}
</pre>

2. https://github.com/conwetlab/ckanext-right_time_context/blob/master/ckanext/right_time_context/templates/package/snippets/resource_item.html

<pre>
**Line No 15:**
{% if res.url.lower().find('/querycontext')== -1 and res.url.lower().find('/contextentities/')== -1 %}
</pre>

We found that these entries are only for V1 and these are hiding the "Go to Resource" button on that screen. It is working fine for V1, but for  there is no source  code for `V2 entities and /op/query/`.

**Comment by Labuschagne-Miro** [comment]
@nisha-nec I think you should close this issue. Pull request is already merged.

**Comment by Nisha1293** [comment]
I am closing this issue, as PR is already merged.
